function menu () {
    const theContainer = document.querySelector("#content");
    theContainer.innerHTML = "";
    const theMenuContainer = document.createElement("div");
    theMenuContainer.classList.add("menuContainer");
    const theBlankLeft = document.createElement("div");
    theBlankLeft.classList.add("blankLeft");
    const theBlankRight = document.createElement("div");
    theBlankRight.classList.add("blankRight");
    const theMenuInformation = document.createElement("div");
    theMenuInformation.classList.add("menuInformation");
    const theMenuTitle = document.createElement("header");
    theMenuTitle.classList.add("menuTitle");
    theMenuInformation.appendChild(theMenuTitle);
    //Breakfast begin
    const theBreakfastTitle = document.createElement("div");
    const theBreakfast1 = document.createElement("div");
    const theBreakfastPrice1 = document.createElement("div");
    const theBreakfastDescription1 = document.createElement("div");
    theBreakfastTitle.classList.add("breakfastTitle");
    theBreakfast1.classList.add("breakfast1");
    theBreakfastDescription1.classList.add("breakfastDescription1");
    theBreakfastPrice1.classList.add("breakfastPrice1");
    const theBreakfast2 = document.createElement("div");
    const theBreakfastPrice2 = document.createElement("div");
    const theBreakfastDescription2 = document.createElement("div");
    theBreakfast2.classList.add("breakfast2");
    theBreakfastDescription2.classList.add("breakfastDescription2");
    theBreakfastPrice2.classList.add("breakfastPrice2");
    theMenuTitle.textContent = "Ivanovichi-s menu";
    theBreakfastTitle.textContent = "Breakfasts";
    theBreakfast1.textContent = "Pancake Delight";
    theBreakfastDescription1.textContent = "Fluffy pancakes topped with fresh berries, maple syrup, and a dollop of whipped cream.";
    theBreakfastPrice1.textContent = "$8.99";
    theBreakfast2.textContent = "Avocado Toast Special ";
    theBreakfastDescription2.textContent = "Whole-grain toast with smashed avocado, cherry tomatoes, and a poached egg.";
    theBreakfastPrice2.textContent = "$7.49";
    //Breakfast finish
    //Dinner begin
    const theDinnerTitle = document.createElement("div");
    const theDinner1 = document.createElement("div");
    const theDinnerPrice1 = document.createElement("div");
    const theDinnerDescription1 = document.createElement("div");
    theDinnerTitle.classList.add("dinnerTitle");
    theDinner1.classList.add("dinner1");
    theDinnerDescription1.classList.add("dinnerDescription1");
    theDinnerPrice1.classList.add("dinnerPrice1");
    const theDinner2 = document.createElement("div");
    const theDinnerPrice2 = document.createElement("div");
    const theDinnerDescription2 = document.createElement("div");
    theDinner2.classList.add("dinner2");
    theDinnerDescription2.classList.add("dinnerDescription2");
    theDinnerPrice2.classList.add("dinnerPrice2");
    theDinnerTitle.textContent = "Dinners";
    theDinner1.textContent = "Grilled Salmon Plate";
    theDinnerDescription1.textContent = "Juicy grilled salmon served with roasted vegetables and garlic mashed potatoes.";
    theDinnerPrice1.textContent = "$14.99";
    theDinner2.textContent = "Spaghetti Bolognese";
    theDinnerDescription2.textContent = "Classic Italian pasta with rich, slow-cooked meat sauce and Parmesan cheese. ";
    theDinnerPrice2.textContent = "$12.99";
    //Dinner finish
    //Drinks start
    const theDrinksTitle = document.createElement("div");
    const theDrinks1 = document.createElement("div");
    const theDrinksPrice1 = document.createElement("div");
    const theDrinksDescription1 = document.createElement("div");
    theDrinksTitle.classList.add("drinksTitle");
    theDrinks1.classList.add("drinks1");
    theDrinksDescription1.classList.add("drinksDescription1");
    theDrinksPrice1.classList.add("drinksPrice1");
    const theDrinks2 = document.createElement("div");
    const theDrinksPrice2 = document.createElement("div");
    const theDrinksDescription2 = document.createElement("div");
    theDrinks2.classList.add("drinks2");
    theDrinksDescription2.classList.add("drinksDescription2");
    theDrinksPrice2.classList.add("drinksPrice2");
    theDrinksTitle.textContent = "Drinks";
    theDrinks1.textContent = "Fresh Orange Juice ";
    theDrinksDescription1.textContent = "Cold-pressed orange juice for a refreshing vitamin boost.";
    theDrinksPrice1.textContent = "$4.99";
    theDrinks2.textContent = "Iced Caramel Latte";
    theDrinksDescription2.textContent = "Smooth espresso with caramel syrup, milk, and ice. ";
    theDrinksPrice2.textContent = "$5.49";
    //Drinks finnish
    theBreakfast1.appendChild(theBreakfastDescription1);
    theBreakfast2.appendChild(theBreakfastDescription2);
    theDinner1.appendChild(theDinnerDescription1);
    theDinner2.appendChild(theDinnerDescription2);
    theDrinks1.appendChild(theDrinksDescription1);
    theDrinks2.appendChild(theDrinksDescription2);
    theMenuContainer.appendChild(theBlankLeft);
    theMenuContainer.appendChild(theBlankRight);
    theMenuContainer.appendChild(theMenuInformation);
    theContainer.appendChild(theMenuContainer);
    theMenuInformation.appendChild(theBreakfastTitle);
    theMenuInformation.appendChild(theBreakfast1);
    theMenuInformation.appendChild(theBreakfastPrice1);
    theMenuInformation.appendChild(theBreakfast2);
    theMenuInformation.appendChild(theBreakfastPrice2);
    theMenuInformation.appendChild(theDinnerTitle);
    theMenuInformation.appendChild(theDinner1);
    theMenuInformation.appendChild(theDinnerPrice1);
    theMenuInformation.appendChild(theDinner2);
    theMenuInformation.appendChild(theDinnerPrice2);
    theMenuInformation.appendChild(theDrinksTitle);
    theMenuInformation.appendChild(theDrinks1);
    theMenuInformation.appendChild(theDrinksPrice1);
    theMenuInformation.appendChild(theDrinks2);
    theMenuInformation.appendChild(theDrinksPrice2);
};

export{menu};